bundler_args: --without assets:development:production
language: ruby
rvm:
  - 2.1.1
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database ohana_api_test;' -U postgres
  - psql -U postgres -q -d ohana_api_test -f db/structure.sql
  - cp config/database.travis.yml config/database.yml
script: "bundle exec rake"
env:
  global:
    - S3_BUCKET_NAME=gems-for-travis
    - ADMIN_APP_TOKEN=testing123
    - BASE_DOMAIN=example.com
    - API_PATH=api
    - DEFAULT_PER_PAGE=30
    - MAX_PER_PAGE=50
    - secure: "Zf09T1x9K8uzJPDQvdBv17XXnSh0DL8V/akzz8oRE6KfZWHlIhskqdygRyHeL4VNVndn2nvWQec8Md0nnYv+VeKASqPRBuXoaFizJBy/fvYCgTdw65puYFokF1tPFRzlrm4JiDDHJScb46eYShUzdhugsrL6cuwJJQs8ZZYYSWI="
